apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: naseemahmad244/posts
        env:
        - name: EVENTBUS_SERVICE_NAME
          value: eventbus-clusterip-service
        - name: EVENTBUS_PORT
          value: "4004"
        - name: POSTS_PORT
          value: "4000"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-service
spec:
  selector:
    app: posts
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: posts-nodeport-service
# spec:
#   selector:
#     app: posts
#   ports:
#   - port: 4000
#     targetPort: 4000
#     protocol: TCP
#   type: NodePort

